### PR TITLE
List tasks by tag

### LINKED ISSUE #250: [#7 TES 1.1 Spec compliance] Validate the response against filter-1
**Describe the bug**
TES does not implement the new filter added in TES 1.1 list tasks

**Steps to Reproduce**
Run the TES compliance test for TES 1.1

**Expected behavior**
The `Filter-1` test case passes.

**Additional context**
Currently, the test case message says: `Filter-1 failed for GET /tasks due to invalid filter type`

### LINKED ISSUE #337: Implement ListTasks by tag_key
Implement ListTasks by tag_key (currently not supported), i.e.

`?tag_key=foo1&tag_value=bar1&tag_key=foo2&tag_value=bar2`

Spec:
https://github.com/ga4gh/task-execution-schemas/blob/1df37d34242f74d3f03475c6b9de3324b8094054/openapi/task_execution_service.openapi.yaml#L114

Thank you @jlester-msft for identifying this.

### PR DESCRIPTION
**Pull request by MattMcL4475**
fixes #337 
fixes #250

Uses raw SQL to handle querying PostgreSQL column type of `jsonb` by tags.  Also adds a GIN index to TesTasks.Json.Tags

### CODE REVIEW

**Comment by MattMcL4475** [comment]
@BMurri please implement pagination and any refactoring to better align with the existing implementation

File: src/Tes/Repository/PostgreSqlCachingRepository.cs [hunk 1]
```diff
@@ -97,6 +101,48 @@ protected async Task<IEnumerable<T>> GetItemsAsync(DbSet<T> dbSet, Expression<Fu
...
         }
 
+        protected async Task<IEnumerable<TesTaskDatabaseItem>> GetTesTaskDatabaseItemsByTagAsync(
+            TesDbContext dbContext,
+            Dictionary<string, string> tags,
+            CancellationToken cancellationToken)
+        {
+            ArgumentNullException.ThrowIfNull(dbContext);
+            ArgumentNullException.ThrowIfNull(tags);
+            if (tags.Count == 0) throw new ArgumentOutOfRangeException("Must specify more than one tag");
```
Comment (BMurri) [inline src/Tes/Repository/PostgreSqlCachingRepository.cs:111]: "Must specify _**at least**_ one tag"?

File: src/Tes/Repository/PostgreSqlCachingRepository.cs [hunk 2]
```diff
@@ -97,6 +101,48 @@ protected async Task<IEnumerable<T>> GetItemsAsync(DbSet<T> dbSet, Expression<Fu
...
+
+            var sqlBuilder = new StringBuilder();
+            sqlBuilder.AppendLine("SELECT * FROM TesTasks WHERE ");
+            var tagConditions = tags.Select(kvp => $"\"Json\"->'Tags'->>'{kvp.Key}' = @p_{kvp.Key}");
```
Comment (BMurri) [inline src/Tes/Repository/PostgreSqlCachingRepository.cs:115]: To prevent SQL injection, should we do any validation on each `Key`? Or, can we pass in the keys as command parameters?

File: src/Tes/Repository/PostgreSqlCachingRepository.cs [hunk 3]
```diff
@@ -97,6 +101,48 @@ protected async Task<IEnumerable<T>> GetItemsAsync(DbSet<T> dbSet, Expression<Fu
...
+
+            using var connection = dbContext.Database.GetDbConnection();
+            await connection.OpenAsync();
+
+            using var command = connection.CreateCommand();
+            command.CommandText = sqlBuilder.ToString();
+
+            foreach (var tag in tags)
+            {
+                command.Parameters.Add(new NpgsqlParameter($"p_{tag.Key}", tag.Value));
```
Comment (BMurri) [inline src/Tes/Repository/PostgreSqlCachingRepository.cs:126]: According to the spec, if the provided tag.Value is empty, then the query should return all tasks with the provided tag.Key no matter what the value might be. This query does not appear to me to do that.

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 4]
```diff
@@ -159,6 +159,13 @@ public virtual async Task<IActionResult> CreateTaskAsync([FromBody] TesTask tesT
                 ?.Skip(2)
                 ?.FirstOrDefault();
 
+            if (tesTask.Tags == null)
+            {
+                tesTask.Tags = new Dictionary<string, string>();
+            }
+
+            tesTask.Tags["workflow_id"] = tesTask.WorkflowId;
```
Comment (BMurri) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:167]: For the tags we add, we may want to consider using the [set added here](https://github.com/microsoft/tes-azure/blob/11b3b4d2d40f73c4e758c99629ae6dd1b815465d/api-server/tesazure/backends/common/__init__.py#L130C1-L134C105)

Comment (MattMcL4475) [reply src/TesApi.Web/Controllers/TaskServiceApi.cs:167]: Started a new thread with the TES folks on what would be canonical, also which casing makes most sense ("workflowId" might be more canonical since JSON is typically camel case).

File: src/Tes/Repository/PostgreSqlCachingRepository.cs (hunk 2 above)
Comment (MattMcL4475) [reply src/Tes/Repository/PostgreSqlCachingRepository.cs:115]: Agreed will need to research this more.  Will depend on what Npgsql supports.  Presumably there is a way to do this. but not sure since it's a JSON query

File: src/TesApi.Web/Controllers/TaskServiceApi.cs (hunk 4 above)
Comment (MattMcL4475) [reply src/TesApi.Web/Controllers/TaskServiceApi.cs:167]: confirmed that TES uses snake case for tag keys to be consistent

Comment (BMurri) [reply src/TesApi.Web/Controllers/TaskServiceApi.cs:167]: The thing is that these tags are intended for the customer to populate and we are intruding on their space here. It is accepted internet convention to do the x-organization-other-things-here pattern for naming things in other people's namespaces. We don't want collisions

File: src/Tes/Repository/TesTaskPostgreSqlRepository.cs [hunk 5]
```diff
@@ -309,19 +280,17 @@ private async Task<TesTaskDatabaseItem> GetItemFromCacheOrDatabase(string id, bo
...
         {
-            // It turns out, PostgreSQL doesn't handle EF's interpretation of ORDER BY more then one "column" in any resonable way, so we have to order by the only thing we have that is expected to be unique.
-            //orderBy = pagination is null ? orderBy : q => q.OrderBy(t => t.Json.CreationTime).ThenBy(t => t.Json.Id);
-            orderBy = pagination is null ? orderBy : q => q.OrderBy(t => t.Json.Id);
-
             using var dbContext = CreateDbContext();
-            return (await GetItemsAsync(dbContext.TesTasks, WhereTesTask(predicate), cancellationToken, orderBy, pagination)).Select(item => EnsureActiveItemInCache(item, t => t.Json.Id, t => t.Json.IsActiveState()).Json);
+            return (await GetItemsAsync(dbContext.TesTasks, /*readerFunc, */cancellationToken, orderBy, pagination, WhereTesTask(efPredicate), rawPredicate))
```
Comment (MattMcL4475) [inline src/Tes/Repository/TesTaskPostgreSqlRepository.cs:292]: remove this comment?

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 6]
```diff
@@ -287,28 +292,187 @@ public virtual async Task<IActionResult> GetTaskAsync([FromRoute][Required] stri
...
+            {
+                if (tagKeys?.Length > 0)
+                {
+                    var (zippedTags, error) = ParseZipedTagsFromQuery();
+
+                    if (string.IsNullOrEmpty(error))
+                    {
+                        tags = zippedTags;
+                    }
+                    else if (tagKeys.Length == tagValues?.Length)
```
Comment (MattMcL4475) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:331]: Seems like this should be a bad request; is there a scenario where it's not?

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 7]
```diff
@@ -287,28 +292,187 @@ public virtual async Task<IActionResult> GetTaskAsync([FromRoute][Required] stri
...
+                        {
+                            return (null, "Unmatched tag_value");
+                        }
+
+                        list[^1] = (list[^1].Key, new(encodedPair.DecodeValue().Span));
+                        break;
+                }
+            }
+
+            // TODO: should tag keys be case sensitive or case insensitive? I would argue for case sensitive, as that is the default for JSON.
```
Comment (MattMcL4475) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:409]: Tag keys should be case insensitive

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 8]
```diff
@@ -287,28 +292,187 @@ public virtual async Task<IActionResult> GetTaskAsync([FromRoute][Required] stri
...
+            var tags = new Dictionary<string, string>(StringComparer.Ordinal); // StringComparer.OrdinalIgnoreCase
```
Comment (MattMcL4475) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:410]: is this the only place that needs to change for tag keys to be case insensitive?

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 9]
```diff
@@ -330,29 +494,97 @@ private async ValueTask<bool> TryRemoveItemFromCacheAsync(TesTask tesTask, strin
...
+                        continue;
+                    }
+
+                    return s.GetArgument(index);
+                }
+
+                return null;
+            }
+
+            public override object[] GetArguments() // TODO: object is nullable
```
Comment (MattMcL4475) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:579]: TODO?

File: src/TesApi.Web/Controllers/TaskServiceApi.cs [hunk 10]
```diff
@@ -330,29 +494,97 @@ private async ValueTask<bool> TryRemoveItemFromCacheAsync(TesTask tesTask, strin
...
+            {
+                return strings.SelectMany(s => s.GetArguments()).ToArray();
+            }
 
-            return jsonResult;
+            public override string ToString(IFormatProvider formatProvider) // TODO: IFormatProvider is nullable
```
Comment (MattMcL4475) [inline src/TesApi.Web/Controllers/TaskServiceApi.cs:584]: TODO?

**Review by BMurri — APPROVED** [review]
Approved per @MattMcL4475
